server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    active: aggregation
    # active: dev
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ${GATEWAY_REDIS_PASSWORD:your_gateway_redis_password}
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
