server:
  port: 8001

spring:
  application:
    name: short-link-project
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ${PROJECT_REDIS_PASSWORD:your_project_redis_password}
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: ${PROJECT_RABBITMQ_PASSWORD:your_project_rabbitmq_password}
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

short-link:
  domain:
    default: heng.beimxw.top
  stats:
    locale:
      amap-key: ${PROJECT_AMAP_KEY:your_project_amap_key}
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
